apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyego-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eyego
  template:
    metadata:
      labels:
        app: eyego
    spec:
      containers:
      - name: eyego
        image: 162717643593.dkr.ecr.us-east-1.amazonaws.com/eyego-app:latest
        ports:
        - containerPort: 3000
